services:
  - type: web
    name: sicbo-predictor
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TRUM_AI_DATA
          property: connectionString
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true
